<a href="https://colab.research.google.com/github/simran12m/Codedex_hackathon/blob/main/track3_simranbola.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

In [3]:
athelets_df= pd.read_csv('https://raw.githubusercontent.com/rgriff23/Olympic_history/master/data/athlete_events.csv')
athelets_df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [5]:
athelets_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [6]:
athelets_df.describe()

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

In [7]:
df_noc= pd.read_csv('https://raw.githubusercontent.com/rgriff23/Olympic_history/master/data/noc_regions.csv')
df_noc

     NOC       region                 notes
0    AFG  Afghanistan                   NaN
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                   NaN
3    ALG      Algeria                   NaN
4    AND      Andorra                   NaN
..   ...          ...                   ...
225  YEM        Yemen                   NaN
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                   NaN
229  ZIM     Zimbabwe                   NaN

[230 rows x 3 columns]

In [8]:
df_noc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NOC     230 non-null    object
 1   region  227 non-null    object
 2   notes   21 non-null     object
dtypes: object(3)
memory usage: 5.5+ KB

In [9]:
df_noc= df_noc.drop(['notes'], axis=1)
df_noc

     NOC       region
0    AFG  Afghanistan
1    AHO      Curacao
2    ALB      Albania
3    ALG      Algeria
4    AND      Andorra
..   ...          ...
225  YEM        Yemen
226  YMD        Yemen
227  YUG       Serbia
228  ZAM       Zambia
229  ZIM     Zimbabwe

[230 rows x 2 columns]

In [10]:
final_df= pd.merge(athelets_df, df_noc, how='left', on='NOC')
final_df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN,Poland
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Poland
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Poland
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN,Poland
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN,Poland

In [11]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 16 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
 15  region  270746 non-null  object
dtypes: float64(3), int64(2), object(11)
memory usage: 33.1+ MB

In [12]:
final_df.describe()

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

In [13]:
final_df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
region       370
dtype: int64

Filing the missing values:

In [14]:
final_df['Age'].fillna(value=final_df['Age'].mean(),inplace=True)

In [15]:
final_df['Height'].fillna(value=final_df['Height'].mean(),inplace=True)

In [16]:
final_df['Weight'].fillna(value=final_df['Weight'].mean(),inplace=True)

In [17]:
final_df['region'].fillna(value="Region Unknown",inplace=True)

In [18]:
final_df['Medal'].fillna(value="No Medal",inplace=True)

In [19]:
final_df.isnull().sum()

ID        0
Name      0
Sex       0
Age       0
Height    0
Weight    0
Team      0
NOC       0
Games     0
Year      0
Season    0
City      0
Sport     0
Event     0
Medal     0
region    0
dtype: int64

In [20]:
final_df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
271111    False
271112    False
271113    False
271114    False
271115    False
Length: 271116, dtype: bool

In [21]:
final_df.duplicated().sum()

1385

In [ ]:
final_df.drop_duplicates(keep='first',inplace=True)

#Exploratory Data Analysis

Medal distribution by country

In [24]:
fig_df= final_df[final_df['Medal'].notna()].groupby('NOC')['Medal'].count().sort_values(ascending=False).reset_index().head(10)
fig= px.bar(fig_df, barmode='stack', color= 'Medal' ,title='Medal Distribution by Country')
fig.show()

Top 10 Gold,Silver and Bronze Winning Nations

In [25]:
medal_df=final_df[final_df['Medal']=="Gold"].groupby(["Team"]).count().sort_values(by='ID', ascending=False).reset_index()
medal_df.head(10)

,Team,ID,Name,Sex,Age,Height,Weight,NOC,Games,Year,Season,City,Sport,Event,Medal,region
0,United States,2474,2474,2474,2474,2474,2474,2474,2474,2474,2474,2474,2474,2474,2474,2474
1,Soviet Union,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058
2,Germany,679,679,679,679,679,679,679,679,679,679,679,679,679,679,679
3,Italy,535,535,535,535,535,535,535,535,535,535,535,535,535,535,535
4,Great Britain,519,519,519,519,519,519,519,519,519,519,519,519,519,519,519
5,France,455,455,455,455,455,455,455,455,455,455,455,455,455,455,455
6,Sweden,451,451,451,451,451,451,451,451,451,451,451,451,451,451,451
7,Hungary,432,432,432,432,432,432,432,432,432,432,432,432,432,432,432
8,Canada,422,422,422,422,422,422,422,422,422,422,422,422,422,422,422
9,East Germany,369,369,369,369,369,369,369,369,369,369,369,369,369,369,369

In [28]:
gold_plot = px.pie(medal_df.head(10), values='ID',hole=0.6, names='Team', title='<b>Top 10 Gold Winning Nations</b>',color='Team',template = "none")
fig.update_layout(plot_bgcolor = " whitesmoke")
gold_plot.show()

In [29]:
silver_df=final_df[final_df['Medal']=="Silver"].groupby(["Team"]).count().sort_values(by='ID', ascending=False).reset_index()
silver_df.head(10)

,Team,ID,Name,Sex,Age,Height,Weight,NOC,Games,Year,Season,City,Sport,Event,Medal,region
0,United States,1512,1512,1512,1512,1512,1512,1512,1512,1512,1512,1512,1512,1512,1512,1512
1,Soviet Union,716,716,716,716,716,716,716,716,716,716,716,716,716,716,716
2,Germany,627,627,627,627,627,627,627,627,627,627,627,627,627,627,627
3,Great Britain,582,582,582,582,582,582,582,582,582,582,582,582,582,582,582
4,France,518,518,518,518,518,518,518,518,518,518,518,518,518,518,518
5,Italy,508,508,508,508,508,508,508,508,508,508,508,508,508,508,508
6,Sweden,476,476,476,476,476,476,476,476,476,476,476,476,476,476,476
7,Australia,453,453,453,453,453,453,453,453,453,453,453,453,453,453,453
8,Canada,413,413,413,413,413,413,413,413,413,413,413,413,413,413,413
9,Russia,351,351,351,351,351,351,351,351,351,351,351,351,351,351,351

In [31]:
silver_plot = px.pie(silver_df.head(10), values='ID',hole=0.6, names='Team', title='<b>Top 10 Silver Winning Nations</b>',color='Team',template = "none")
fig.update_layout(plot_bgcolor = " whitesmoke")
silver_plot.show()

In [32]:
bronze_df=final_df[final_df['Medal']=="Bronze"].groupby(["Team"]).count().sort_values(by='ID', ascending=False).reset_index()
bronze_df.head(10)

,Team,ID,Name,Sex,Age,Height,Weight,NOC,Games,Year,Season,City,Sport,Event,Medal,region
0,United States,1233,1233,1233,1233,1233,1233,1233,1233,1233,1233,1233,1233,1233,1233,1233
1,Germany,678,678,678,678,678,678,678,678,678,678,678,678,678,678,678
2,Soviet Union,677,677,677,677,677,677,677,677,677,677,677,677,677,677,677
3,France,577,577,577,577,577,577,577,577,577,577,577,577,577,577,577
4,Great Britain,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572
5,Australia,511,511,511,511,511,511,511,511,511,511,511,511,511,511,511
6,Sweden,507,507,507,507,507,507,507,507,507,507,507,507,507,507,507
7,Italy,484,484,484,484,484,484,484,484,484,484,484,484,484,484,484
8,Finland,415,415,415,415,415,415,415,415,415,415,415,415,415,415,415
9,Canada,408,408,408,408,408,408,408,408,408,408,408,408,408,408,408

In [33]:
bronze_plot = px.pie(bronze_df.head(10), values='ID',hole=0.6, names='Team', title='<b>Top 10 Bronze Winning Nations</b>',color='Team',template = "none")
fig.update_layout(plot_bgcolor = " whitesmoke")
bronze_plot.show()